app:
  baseUrl: ${APP_BASE_URL}

backend:
  baseUrl: ${BACKEND_BASE_URL}
  listen: ':7007'
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

permission:
  enabled: false

catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Domain, Group, User, Template]
  locations:
    - type: file
      target: ./catalog-entities/all.yaml
    - type: file
      target: ./templates/nodejs-service/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./templates/aws-s3-bucket/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ./templates/aws-ecs-spot/template.yaml
      rules:
        - allow: [Template]
