image:
  repository: ghcr.io/jmarcelotse/app-nxt
  tag: latest
  pullPolicy: Always

replicas: 2

service:
  type: ClusterIP
  port: 7007

ingress:
  enabled: false
  # host: backstage.example.com
  # tls: true

env:
  APP_BASE_URL: "http://localhost:7007"
  BACKEND_BASE_URL: "http://localhost:7007"

postgresql:
  host: app-nxt-postgresql
  port: "5432"
  user: backstage
  password: backstage

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
